FROM nextcloud:28.0.2

RUN apt-get update && apt-get install -y smbclient && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y libbz2-dev && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

RUN usermod -a -G 100 www-data
