---
- name: Configure Home Server
  hosts: home_servers
  become: yes
  roles:
    - role: common
      tags: ['common', 'setup']
    - role: docker_network
      tags: ['docker_network', 'setup']
    - role: newt
      tags: ['newt']
    - role: big_agi
      tags: ['big_agi']
    - role: openspeedtest
      tags: ['openspeedtest']
    - role: vaultwarden
      tags: ['vaultwarden']
    - role: ofelia
      tags: ['ofelia']
    - role: paperless
      tags: ['paperless']
    - role: nextcloud
      tags: ['nextcloud']
