# tasks file for deploy_app role
- name: Ensure the deployment directory exists and has correct ownership
  ansible.builtin.file:
    path: "{{ app_deploy_path }}"
    state: directory
    owner: "{{ app_owner }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Construct Git repository URL with credentials
  ansible.builtin.set_fact:
    authenticated_git_repo_url: "https://{{ git_repo_username | urlencode }}:{{ git_repo_pat | urlencode }}@{{ git_repo_url_base }}"
  no_log: true

- name: Clone or update the private repository
  ansible.builtin.git:
    repo: "{{ authenticated_git_repo_url }}"
    dest: "{{ app_deploy_path }}"
    version: "{{ git_repo_branch }}"
    accept_hostkey: yes # For SSH, not strictly needed for HTTPS but good to be aware of
    force: yes
    update: yes # Pulls changes if the repo already exists
  become: no # Run this task as the ansible_user (e.g., azureuser), not root
  no_log: false

# Example: If your app needs specific file permissions after cloning
# - name: Ensure correct permissions for app files (example)
#   ansible.builtin.file:
#     path: "{{ app_deploy_path }}"
#     owner: "{{ app_owner }}"
#     group: "{{ app_group }}"
#     recurse: yes
#   become: yes # May need to become root to chown if files were created by a different process
