- name: Ensure Pangolin base and config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root # Or your deployment user
    group: root # Or your deployment user
    mode: '0755'
  loop:
    - "{{ pangolin_deploy_dir }}"
    - "{{ pangolin_config_dir }}"
    - "{{ pangolin_traefik_config_dir }}"

- name: Copy Traefik dynamic configuration
  ansible.builtin.copy:
    src: dynamic_config.yml.j2
    dest: "{{ pangolin_traefik_config_dir }}/dynamic_config.yml"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Pangolin stack # If you add a handler

- name: Copy Traefik main configuration
  ansible.builtin.copy:
    src: traefik_config.yml.j2
    dest: "{{ pangolin_traefik_config_dir }}/traefik_config.yml"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Pangolin stack # If you add a handler

- name: Template Pangolin main config.yml
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ pangolin_config_dir }}/config.yml"
    owner: root
    group: root
    mode: '0640' # Slightly more restrictive as it contains secrets indirectly
  notify: Restart Pangolin stack # If you add a handler

- name: Copy Docker Compose file for Pangolin
  ansible.builtin.copy:
    src: "{{ pangolin_local_compose_file }}"
    dest: "{{ pangolin_deploy_dir }}/compose.yml"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Pangolin stack # If you add a handler

- name: Deploy Pangolin Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ pangolin_deploy_dir }}"
    project_name: "{{ pangolin_compose_project_name }}"
    state: present
    pull: "{{ pangolin_pull_images }}"
    recreate: "{{ pangolin_recreate_services }}" # 'always', 'never', 'smart'
    remove_orphans: true
  register: pangolin_compose_status
  # Note: The docker_compose_v2 module handles changes intelligently.
  # It will only restart containers if the compose file or related configs change.
  # The 'notify' on previous tasks ensures that if a config file changes,
  # the handler (if defined) can explicitly restart, or you can rely on docker_compose_v2.

- name: Display Pangolin deployment status
  ansible.builtin.debug:
    var: pangolin_compose_status
    verbosity: 1 # Show only if -v is used
