# roles/vaultwarden/tasks/main.yml
---
- name: "Vaultwarden | Ensure directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ services.vaultwarden.data_dir }}"
    - "{{ services.vaultwarden.volume_dir }}"

- name: "Vaultwarden | Ask if restore is needed"
  ansible.builtin.pause:
    prompt: "Restore Vaultwarden from backup? (yes/no)"
  register: restore_prompt
  when: vaultwarden_restore is not defined

- name: "Vaultwarden | Set restore flag"
  ansible.builtin.set_fact:
    do_restore: "{{ vaultwarden_restore | default(restore_prompt.user_input | default('no')) | bool }}"

- name: "Vaultwarden | Get snapshot ID for restore"
  ansible.builtin.pause:
    prompt: "Snapshot ID (press Enter for 'latest', or specify like 'c53a4d40')"
  register: snapshot_prompt
  when: do_restore

- name: "Vaultwarden | Set snapshot ID"
  ansible.builtin.set_fact:
    snapshot_id: "{{ snapshot_prompt.user_input if (snapshot_prompt.user_input is defined and snapshot_prompt.user_input != '') else 'latest' }}"
  when: do_restore

- name: "Vaultwarden | Stop Vaultwarden application before restore"
  community.docker.docker_compose_v2:
    project_src: "{{ services.vaultwarden.data_dir }}"
    files: ["docker-compose.yml"]
    project_name: "{{ services.vaultwarden.name }}"
    state: absent
  ignore_errors: true
  when: do_restore

- name: "Vaultwarden | Stop backup containers before restore"
  community.docker.docker_compose_v2:
    project_src: "{{ services.vaultwarden.data_dir }}"
    files: ["backup-compose.yml"]
    project_name: "{{ services.vaultwarden.name }}_backup"
    state: absent
  ignore_errors: true
  when: do_restore

- name: "Vaultwarden | Restore from backup"
  ansible.builtin.command: >-
    docker run --rm
    --name vaultwarden_restore_temp
    -e RESTIC_REPOSITORY={{ services.vaultwarden.restic_repository }}
    -e RESTIC_PASSWORD={{ restic_password }}
    -e B2_ACCOUNT_ID={{ b2_account_id }}
    -e B2_ACCOUNT_KEY={{ b2_account_key }}
    -v "{{ services.vaultwarden.volume_dir }}:{{ services.vaultwarden.backup_container_path }}:rw"
    --entrypoint /sbin/tini
    {{ restic_image }}
    --
    sh -c "
    echo '=== Starting Vaultwarden restore process ===' &&
    echo 'Repository: {{ services.vaultwarden.restic_repository }}' &&
    echo 'Snapshot: {{ snapshot_id }}' &&
    echo '=== Checking repository ===' &&
    restic snapshots --no-lock &&
    echo '=== Clearing target directory ===' &&
    rm -rf /vaultwarden-data/* /vaultwarden-data/.* 2>/dev/null || true &&
    echo '=== Restoring snapshot ===' &&
    restic restore {{ snapshot_id }} --target / --path {{ services.vaultwarden.backup_container_path }} --verbose &&
    echo '=== Verifying restored files ===' &&
    ls -la /vaultwarden-data &&
    echo '=== Vaultwarden restore completed ==='
    "
  no_log: false
  when: do_restore

- name: "Vaultwarden | Deploy backup containers"
  ansible.builtin.template:
    src: resticker-vaultwarden-compose.yml.j2
    dest: "{{ services.vaultwarden.data_dir }}/backup-compose.yml"

- name: "Vaultwarden | Start backup stack"
  community.docker.docker_compose_v2:
    project_src: "{{ services.vaultwarden.data_dir }}"
    files: ["backup-compose.yml"]
    project_name: "{{ services.vaultwarden.name }}_backup"
    state: present

- name: "Vaultwarden | Deploy application"
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ services.vaultwarden.data_dir }}/docker-compose.yml"

- name: "Vaultwarden | Start Vaultwarden"
  community.docker.docker_compose_v2:
    project_src: "{{ services.vaultwarden.data_dir }}"
    files: ["docker-compose.yml"]
    project_name: "{{ services.vaultwarden.name }}"
    state: present
